version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
      - ./static:/app/static
    environment:
      - FLASK_ENV=development
    restart: always
