name: build-and-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # 👈 Important: this uses your local Minikube machine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/sunrise-backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/sunrise-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/sunrise-frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/sunrise-frontend:latest

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/
          kubectl rollout restart deployment backend-deployment
          kubectl rollout restart deployment frontend-deployment

      - name: Print who triggered the build
        run: echo "Triggered by ${{ github.actor }}"

